#!/bin/bash
#look for a VirtualHost in Apacheconfig and find the corresponding DocumentRoot.

WEBSITE=$1
FILE=$2
sed -n "/VirtualHost/{:a;N;/\/VirtualHost/!ba; /${WEBSITE}/p}" ${FILE}  ## prints out the VirtualHost-Blocks that contain a Pattern
